decimal = int(input("Enter the number:"))
print("The conversion of decimal number " , decimal , "is:")
print(bin(decimal),"in binary")
print(oct(decimal), "in octa")
print(hex(decimal), "in hexadecimal")
